app/__init__.py
from flask import Flask, render_template

def create_app():
    app = Flask(__name__)

    # import the routes
    from .views import views

    # register the routes
    app.register_blueprint(views, url_prefix='/')

    @app.errorhandler(404)
    def page_not_found(e):
        # note that we set the 404 status explicitly
        return render_template('not_found.html'), 404

    @app.errorhandler(500)
    def internal_server_error(e):
        # note that we set the 404 status explicitly
        return render_template('server_error.html'), 500

    return app

app/views.py
# same as routes.py
# views.py is the file that contains the routes for our app
# We will create a blueprint in this file
# Blueprints are a way to organize related routes in a Flask app
# Blueprints are created in a separate file from the main app
# Blueprints are registered in the main app
import json
import os

from flask import Blueprint, render_template, request, jsonify

from .services.get_data import get_all_data, get_data_page, get_chart_data, get_grouped_products,get_grouped_products_for_simple_charts

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('index.html')


@views.route('/data-table/')
def data_table():
    # Get query parameters with default values
    page = int(request.args.get('page', 1))  # Default to the first page
    items_per_page = int(request.args.get('page_size', 10))  # Default to 10 items per page
    sort_by = request.args.get('sort', None)  # Default is handled in get_data_page
    sort_order = request.args.get('order', 'asc')  # Default to ascending order

    # Specify the CSV file path here
    csv_file = os.path.join('app', 'data', '1000_fake_products.csv')

    # Get the data for the requested page using the get_data_page function
    try:
        data = get_data_page(csv_file, page, items_per_page, sort_by, sort_order)

        # Render the template with the data
        return render_template('data_table.html', **data)
    except FileNotFoundError:
        return "CSV file not found", 404
    except Exception as e:
        return str(e), 500


@views.route('/charts')
def charts():
    try:
        # Using the new function to get aggregated data as a JSON string
        json_data = get_grouped_products_for_simple_charts()

        # Converting JSON string back to Python dictionary
        data = json.loads(json_data)

        # Check if chart headers exist in the data
        if not data['chart_headers']:
            raise Exception('No headers found in data')

        # Dictionary to hold chart data
        charts_data = {}

        # Prepare data for Chart.js
        for header in data['chart_headers']:
            if header != 'category':  # Skipping 'category' header for chart data
                # Extracting values for the current header
                values = [entry[header] for entry in data['chart_data']]

                # Labels are the categories
                labels = [entry['category'] for entry in data['chart_data']]

                # Storing the labels and values for each header
                charts_data[header] = {
                    'labels': labels,
                    'values': values,
                }

        # Return the chart data as a JSON response
        return render_template('charts.html', charts_data=charts_data)


    except FileNotFoundError:
        return jsonify({'error': 'CSV file not found'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@views.route('/old-charts')
def old_charts():
    try:
        data = get_all_data()

        if not data['headers']:
            raise Exception('No headers found in data')

        # Dictionary to hold chart data for each header
        charts_data = {}

        # Prepare data for Chart.js for each header
        for header in data['headers']:
            # Initialize the value counts for each header
            value_counts = {}

            # Count the occurrences of each value for the header
            for entry in data['data']:
                value = entry[header]
                value_counts[value] = value_counts.get(value, 0) + 1

            # Store the labels and sizes for each header
            charts_data[header] = {
                'labels': list(value_counts.keys()),
                'sizes': list(value_counts.values()),
            }

    except FileNotFoundError:
        return render_template('404.html'), 404
    except Exception as e:
        return render_template('server_error.html', error=str(e)), 500

    # Return all headers and their chart data to the template
    return render_template('old_charts.html', headers=data['headers'], charts_data=charts_data)


@views.route('/detailed-charts')
def detailed_charts():
    try:
        # Using the new function to get aggregated data as a JSON string
        json_data = get_grouped_products()

        # Converting JSON string back to Python dictionary
        data = json.loads(json_data)

        # Check if chart headers exist in the data
        if not data['chart_headers']:
            raise Exception('No headers found in data')

        # Dictionary to hold chart data
        charts_data = {}

        # Prepare data for Chart.js
        for header in data['chart_headers']:
            if header != 'category':  # Skipping 'category' header for chart data
                # Extracting values for the current header
                values = [entry[header] for entry in data['chart_data']]

                # Labels are the categories
                labels = [entry['category'] for entry in data['chart_data']]

                # Storing the labels and values for each header
                charts_data[header] = {
                    'labels': labels,
                    'values': values,
                }

        # Return the chart data as a JSON response
        return render_template('detailed_charts.html', charts_data=charts_data)


    except FileNotFoundError:
        return jsonify({'error': 'CSV file not found'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS (Using CDN for simplicity) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Optional: Add custom styles here -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <style>

    </style>
</head>

<body>
    <div id="page-container">
        <!-- Navigation Bar -->
        {% include 'navbar.html' %}

        <div id="content-wrap" class="container mt-5">
            {% block content %}
            {% endblock %}
        </div>

        <!-- import the Footer file -->
        {% include 'footer.html' %}
    </div>

    <!-- Include Bootstrap JS and its dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/charts.html
{% extends 'base.html' %}

{% block title %}Dynamic Chart Types{% endblock %}

{% block content %}

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa; /* Light gray background */
    }
    h1 {
        margin-top: 20px;
    }
    #chart-container {
        width: 60%; /* Adjust the width as needed */
        margin: 20px auto; /* Center the container with margin */
    }
    .select-container {
        text-align: center;
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <h1 class="text-center mb-4 text-primary">Dynamic Charts</h1>
    <div class="select-container d-flex justify-content-center align-items-center flex-wrap">
        <div class="m-2">
            <label for="headerSelect" class="m-2 text-primary">Choose data:</label>
            <select id="headerSelect" class="custom-select">
                <!-- Options will be populated by JavaScript -->
            </select>
        </div>

        <div class="m-2">
            <label for="chartType" class="m-2 text-primary">Choose a chart type:</label>
            <select id="chartType" class="custom-select">
                <option value="pie">Pie Chart</option>
                <option value="bar">Bar Chart</option>
                <option value="line">Line Chart</option>
                <option value="radar">Radar Chart</option>
                <option value="doughnut">Doughnut Chart</option>
                <option value="polarArea">Polar Area Chart</option>
            </select>
        </div>
    </div>
    <div id="chart-container" class="mt-4">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    var allChartData = {{ charts_data | tojson }};
    var headers = Object.keys(allChartData); // Headers are now keys of the allChartData object
    var ctx = document.getElementById('myChart').getContext('2d');
    var currentChart;

    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    function formatHeaderLabel(header) {
        return header.split('_')
                     .map(word => word.charAt(0).toUpperCase() + word.slice(1))
                     .join(' ');
    }

    function createChart(header, type) {
        var data = allChartData[header];

        // Sort data by values in ascending order
        var sortedData = [];
        for (var i = 0; i < data.labels.length; i++) {
            sortedData.push({ label: data.labels[i], value: data.values[i] });
        }
        sortedData.sort(function(a, b) {
            return a.value - b.value;
        });

        var sortedLabels = sortedData.map(function(item) { return item.label; });
        var sortedValues = sortedData.map(function(item) { return item.value; });
        var backgroundColors = sortedLabels.map(() => getRandomColor());
        var formattedHeader = formatHeaderLabel(header); // Format the header for display


        if (currentChart) {
            currentChart.destroy();
        }

        var chartOptions = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                display: type !== 'bar' && type !== 'line' && type !== 'radar',
                labels: {
                    generateLabels: function(chart) {
                        if (chart.config.type === 'bar' || chart.config.type === 'line' || chart.config.type === 'radar') {
                            return []; // return an empty array to hide legend items
                        }
                        return Chart.defaults.global.legend.labels.generateLabels(chart);
                    }
                }
            },
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        };

        currentChart = new Chart(ctx, {
            type: type,
            data: {
                labels: sortedLabels,
                datasets: [{
                    label: formattedHeader,
                    data: sortedValues,
                    backgroundColor: backgroundColors,
                    borderWidth: 1
                }]
            },
            options: chartOptions
        });
    }

    function updateChart() {
        var selectedHeader = document.getElementById('headerSelect').value;
        var selectedType = document.getElementById('chartType').value;
        createChart(selectedHeader, selectedType);
    }

    window.onload = function() {
        var headerSelect = document.getElementById('headerSelect');
        headers.forEach(function(header) {
            var formattedHeader = formatHeaderLabel(header);
            var option = document.createElement('option');
            option.value = header;
            option.text = formattedHeader;
            headerSelect.appendChild(option);
        });

        document.getElementById('chartType').onchange = updateChart;
        headerSelect.onchange = updateChart;

        // Create initial chart
        if (headers.length > 0) {
            createChart(headers[0], document.getElementById('chartType').value);
        }
    }
</script>

{% endblock %}

app/templates/data_table.html
{% extends 'base.html' %}

{% block title %}Data Table{% endblock %}

{% block content %}
    <style>
        .container {
            margin-top: 40px;
         //   background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #007bff; /* Bootstrap primary color */
        }
        table {
            margin-top: 20px;
        }
        th {
            background-color: #007bff; /* Bootstrap primary color */
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .sort-link { /* Class for the sorting links */
            color: white; /* Makes the text color white */
            text-decoration: none; /* No underline for links */
        }
        .sort-link:hover, .sort-link:focus { /* Styles for hover and focus states */
            text-decoration: underline; /* Adds underline on hover/focus for visual feedback */
        }
        .arrow {
            display: inline-block;
            width: 0;
            height: 0;
            margin-left: 5px;
            vertical-align: middle;
            border-style: solid;
        }
        .up {
            border-width: 0 4px 6px 4px;
            border-color: transparent transparent white transparent;
        }
        .down {
            border-width: 6px 4px 0 4px;
            border-color: white transparent transparent transparent;
        }
    </style>

    <div class="container">
        <h1 class="text-center">Data Table</h1>

        <!-- Dropdown for Page Size -->
        <form method="get" action="{{ url_for('views.data_table') }}">
            <label for="page_size">Items per page:</label>
            <select name="page_size" id="page_size" onchange="this.form.submit()">
                {% for size in [10, 20, 50, 100] %}
                    <option value="{{ size }}" {% if size == items_per_page %}selected{% endif %}>{{ size }}</option>
                {% endfor %}
            </select>
        </form>

        <!-- Table to display data -->
        <table class="table table-hover">
            <thead>
                <tr>
                    <!-- Dynamically generate each header cell -->
                    {% for header in headers %}
                    <th>
                        <a class="sort-link"
                        href="?sort={{ header }}&order={{ 'desc' if sort_by == header and sort_order == 'asc' else 'asc' }}&page_size={{ items_per_page }}">
                            {{ header.replace('_', ' ').title() }}
                            <!-- Sorting Arrows -->
                            {% if sort_by == header %}
                                {% if sort_order == 'asc' %}
                                    <span class="arrow up" style="color: red;"></span>
                                {% else %}
                                    <span class="arrow down" style="color: red;"></span>
                                {% endif %}
                            {% else %}
                                <span class="arrow up" style="color: lightgray;"></span>
                                <span class="arrow down" style="color: lightgray;"></span>
                            {% endif %}
                        </a>
                    </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <!-- Dynamically generate each row -->
                {% for entry in data %}
                <tr>
                    {% for header in headers %}
                    <td>{{ entry[header] }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Bottom Pagination Controls -->
        <nav aria-label="Bottom page navigation">
            <ul class="pagination justify-content-center">
                <!-- Link to the first page -->
                <li class="page-item {% if current_page == 1 %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('views.data_table', page=1, page_size=items_per_page) }}">First</a>
                </li>

                <!-- Calculate the range for the pagination -->
                {% set start_page = current_page - 4 if current_page - 4 > 0 else 1 %}
                {% set end_page = start_page + 7 if start_page + 7 <= total_pages else total_pages %}

                <!-- Display the page numbers -->
                {% for i in range(start_page, end_page + 1) %}
                <li class="page-item {% if i == current_page %}active{% endif %}">
                    <a class="page-link" href="{{ url_for('views.data_table', page=i, page_size=items_per_page) }}">{{ i }}</a>
                </li>
                {% endfor %}

                <!-- Link to the last page -->
                <li class="page-item {% if current_page == total_pages %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('views.data_table', page=total_pages, page_size=items_per_page) }}">Last</a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

app/templates/detailed_charts.html
{% extends 'base.html' %}

{% block title %}Dynamic Chart Types{% endblock %}

{% block content %}

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa;
    }
    h1 {
        margin-top: 20px;
    }
    #chart-container {
        width: 80%;
        margin: 20px auto;
    }
</style>

<div class="container">
    <h1 class="text-center mb-4 text-primary">Aggregated Data Chart</h1>
    <div class="select-container d-flex justify-content-center align-items-center flex-wrap">
        <div class="m-2">
            <label for="chartType" class="m-2 text-primary">Choose a chart type:</label>
            <select id="chartType" class="custom-select">
                <option value="bar">Bar Chart</option>
                <!-- Add other chart types if needed -->
            </select>
        </div>
    </div>
    <div id="chart-container">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.0"></script>


<script>
    var allChartData = {{ charts_data | tojson }};
    var headers = Object.keys(allChartData);
    var ctx = document.getElementById('myChart').getContext('2d');
    var currentChart;

    // Define a color for each axis
    var yAxisColors = ['#4e79a7', '#f28e2b', '#e15759'];

    function createChart(type) {
        // Sort labels and values based on 'average_net_profit_percent'
        var profitPercentData = allChartData['average_net_profit_percent'];
        var sortedIndices = profitPercentData.values.map((value, index) => ({ value, index }))
                                                   .sort((a, b) => a.value - b.value)
                                                   .map(data => data.index);

        var sortedLabels = sortedIndices.map(index => profitPercentData.labels[index]);

        var datasets = headers.map(function(header, index) {
            var sortedValues = sortedIndices.map(sortedIndex => allChartData[header].values[sortedIndex]);
            return {
                label: header.replace(/_/g, ' ').replace(/^\w/, c => c.toUpperCase()),
                data: sortedValues,
                backgroundColor: yAxisColors[index % yAxisColors.length],
                borderWidth: 1,
                yAxisID: 'y-axis-' + index
            };
        });

        if (currentChart) {
            currentChart.destroy();
        }

        currentChart = new Chart(ctx, {
            type: type,
            data: {
                labels: sortedLabels,
                datasets: datasets
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                scales: {
                    yAxes: headers.map(function(header, index) {
                        return {
                            id: 'y-axis-' + index,
                            type: 'linear',
                            position: 'left',
                            ticks: {
                                beginAtZero: true,
                                callback: function(value) {
                                    return Math.round(value);
                                }
                            },
                            // Set grid line and tick color for all y-axes
                            gridLines: {
                                display: true,
                                color: yAxisColors[index % yAxisColors.length]
                            },
                            ticks: {
                                fontColor: yAxisColors[index % yAxisColors.length]
                            }
                        };
                    })
                },
                legend: {
                    labels: {
                        fontColor: 'black' // Set this to the color you want for the legend labels
                    }
                }
            }
        });
    }

    window.onload = function() {
        document.getElementById('chartType').onchange = function() {
            createChart(this.value);
        };

        // Initialize chart
        createChart(document.getElementById('chartType').value);
    }
</script>

{% endblock %}

app/templates/footer.html
<!-- Footer -->
<footer class="footer bg-primary text-white">
    <div class="container text-center py-3">
        <span>&copy; 2024 AlexDr</span>
    </div>
</footer>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Python Data Treatment Training{% endblock %}

{% block content %}
<div class="container" style="padding-top: 5%; padding-bottom: 5%;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="text-center display-4 mb-4 text-primary">Python Data Treatment Training Project</h1>
            <h3 class="text-center lead">Exploring the realms of Python, Pandas, Flask, and Data Analysis.</h3>
        </div>
    </div>
<div class="row mt-5">
    <!-- First Column -->
    <div class="col-md-4 text-center">
        <img src="./../static/img/python_and_flask.png" alt="Python and Flask" class="img-fluid rounded mb-3">
    </div>

    <!-- Second Column -->
    <div class="col-md-4 text-center">
        <img src="./../static/img/pandas.png" alt="Pandas" class="img-fluid rounded mb-3">
    </div>
      <div class="col-md-4 text-center">
        <img src="./../static/img/chart.js.jpg" alt="Chart" class="img-fluid rounded mb-3">
    </div>
</div>

</div>
{% endblock %}

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar Example</title>
    <!-- Include Bootstrap CSS for styling -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .navbar-nav .nav-link {
            font-size: 1.25rem;
            padding: 0.5rem 1rem;
        }
    </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/">HOME</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="/data-table/" id="data-table-link">Data Table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/charts" id="charts-link">Simple Charts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/detailed-charts" id="detailed-charts-link">Aggregated Data Charts</a>
                </li>
                <!-- Add other navbar items here -->
            </ul>
        </div>
    </div>
</nav>

<script>
    // Script to add 'active' class to the current page's navbar item
    document.addEventListener('DOMContentLoaded', (event) => {
        let navLinks = document.querySelectorAll('.nav-link');
        let currentLocation = window.location.pathname; // Gets the current page path

        navLinks.forEach((navLink) => {
            if(navLink.getAttribute('href') === currentLocation){
                navLink.classList.add('active');
            } else {
                navLink.classList.remove('active');
            }
        });
    });
</script>

<!-- Include Bootstrap JS and Popper.js for the responsive navbar -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

app/templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>404 Not Found</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="container">
    <div class="text-center">
      <h1 class="display-4 text-danger">404</h1>
      <p class="lead">Oops! The page you were looking for could not be found.</p>
      <p>Please try again with a different URL.</p>
      <a href="/" class="btn btn-primary mt-3">Go to Home</a>
    </div>
  </div>
</body>
</html>

app/templates/old_charts.html
{% extends 'base.html' %}

{% block title %}Dynamic Chart Types{% endblock %}

{% block content %}

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa; /* Light gray background */
    }
    h1 {
        margin-top: 20px;
    }
    #chart-container {
        width: 60%; /* Adjust the width as needed */
        margin: 20px auto; /* Center the container with margin */
    }
    .select-container {
        text-align: center;
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <h1 class="text-center mb-4 text-primary">Dynamic Charts</h1>
    <div class="select-container d-flex justify-content-center align-items-center flex-wrap">
        <div class="m-2">
            <label for="headerSelect" class="m-2 text-primary">Choose data:</label>
            <select id="headerSelect" class="custom-select">
                <!-- Options will be populated by JavaScript -->
            </select>
        </div>

        <div class="m-2">
            <label for="chartType" class="m-2 text-primary">Choose a chart type:</label>
            <select id="chartType" class="custom-select">
                <option value="pie">Pie Chart</option>
                <option value="bar">Bar Chart</option>
                <option value="line">Line Chart</option>
                <option value="radar">Radar Chart</option>
                <option value="doughnut">Doughnut Chart</option>
                <option value="polarArea">Polar Area Chart</option>
            </select>
        </div>
    </div>
    <div id="chart-container" class="mt-4">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    var allChartData = {{ charts_data | tojson }};
    var headers = {{ headers | tojson }};
    var ctx = document.getElementById('myChart').getContext('2d');
    var currentChart;

    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    function createChart(header, type) {
        var data = allChartData[header];

        var sortedData = data.labels.map((label, index) => {
            return { label: label, size: data.sizes[index] };
        }).sort((a, b) => {
            return a.label.localeCompare(b.label);
        });

        var sortedLabels = sortedData.map(d => d.label);
        var sortedSizes = sortedData.map(d => d.size);
        var backgroundColors = sortedLabels.map(() => getRandomColor());

        if (currentChart) {
            currentChart.destroy();
        }

        var chartOptions = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                display: type !== 'bar' && type !== 'line' && type !== 'radar',
                labels: {
                    generateLabels: function(chart) {
                        if (chart.config.type === 'bar' || chart.config.type === 'line' || chart.config.type === 'radar') {
                          return []; // return an empty array to hide legend items
                        }
                        return Chart.defaults.global.legend.labels.generateLabels(chart);
                    }
                }
            },
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        };

        currentChart = new Chart(ctx, {
            type: type,
            data: {
                labels: sortedLabels,
                datasets: [{
                    label: header, // You can set this to an empty string if you don't want labels for tooltips either
                    data: sortedSizes,
                    backgroundColor: backgroundColors,
                    borderWidth: 1
                }]
            },
            options: chartOptions
        });
    }

    function updateChart() {
        var selectedHeader = document.getElementById('headerSelect').value;
        var selectedType = document.getElementById('chartType').value;
        createChart(selectedHeader, selectedType);
    }

    window.onload = function() {
        var headerSelect = document.getElementById('headerSelect');
        headers.forEach(function(header) {
            var option = document.createElement('option');
            option.value = header;
            option.text = header;
            headerSelect.appendChild(option);
        });

        document.getElementById('chartType').onchange = updateChart;
        headerSelect.onchange = updateChart;

        // Create initial chart
        if (headers.length > 0) {
            createChart(headers[0], document.getElementById('chartType').value);
        }
    }
</script>

{% endblock %}